### PR TITLE
fix consumed counter to work on consecutive calls

### LINKED ISSUE #244: Reset consumed property when calling consume().
We have the problem that we call multiple times the consume() method with parameter 1 in the Consumer class. Only the first call works as expected because the consumed property isnt reset but always considered in the maybeStopConsumer method.

I will work on a PR for that.

### PR DESCRIPTION
**Pull request by marco-jantke**
fix #244 

didnt know how to test easily :/

### CODE REVIEW

**Comment by videlalvaro** [comment]
So the idea is to reuse a consumer instance, therefore the `consumer` variable needs to be re initialised ?

**Comment by marco-jantke** [comment]
Yes, we are calling the consume method multiple times in one process. 
Our usecase: we have integration tests where we put messages to a queue and consume them stepwise, asserting a certain state in our system and then consume the next one.

**Comment by videlalvaro** [comment]
Wouldn't it be better to add a resetConsumed() method to prevent BC breaks?

**Comment by marco-jantke** [comment]
For me this seems like expected behavior so I would have fixed it. Tough I see the point of BC breaks.. So its up to you to decide ;-)

**Comment by videlalvaro** [comment]
I think at the beginning it was not thought to call start consumer multiple
times, so I would prefer an extra method call

**Pull request merged**
