### PR TITLE
Support Symfony 3.0

### PR DESCRIPTION
**Pull request by ruudk**

### CODE REVIEW

**Comment by videlalvaro** [comment]
Are you aware of this PR? https://github.com/videlalvaro/RabbitMqBundle/pull/312

**Comment by videlalvaro** [comment]
I think it's better to help in that PR, since they are having trouble on how to handle old PHP versions and so on

**Comment by ruudk** [comment]
Yep, sorry :)

**Comment by ruudk** [comment]
I will try to get it working in this PR , and then comment it on #312

**Comment by ruudk** [comment]
Rebased

**Comment by enachesilviu** [comment]
I gave you access to my fork so you can make additions before the PR is accepted (if ...), added your travis config. Thanks.

**Comment by ruudk** [comment]
@enachesilviu We can also just merge this one, since it's already rebased and clean :)

**Comment by enachesilviu** [comment]
I updated my PR according to your contribution, I agree this one is cleaner. So @videlalvaro should chose to accept one of these PRs if it is the case. I don't care which one.

**Comment by alinalexandru** [comment]
You should try with DependencyInjection < 2.6. The tests are failing.

**Comment by alinalexandru** [comment]
I am trying to fix the tests. The travis yml is inspired from other symfony projects/components
Take I look on my working https://github.com/alinalexandru/RabbitMqBundle/compare/master...alinalexandru:feature/symfony3

**Comment by ruudk** [comment]
@videlalvaro Anything that's blocking the merge of this? Should the Travis file be changed? Other modifications?

**Comment by videlalvaro** [comment]
nope ;-) Thanks!

**Comment by ruudk** [comment]
Awesome. I don't know about your release schedule but a tag would be nice too :) then I can update some other bundles depending on this ;)

**Pull request merged**
